289 possibility to pass custom `axis` label for `g_lineplot`
insightsengineering/goshawk pull request #259
Opened 2024-10-14 11:32 UTC by m7pr

Alternative to https://github.com/insightsengineering/goshawk/pull/250 , related to https://github.com/insightsengineering/teal.goshawk/issues/289

```r
# Example using ADaM structure analysis dataset.

library(stringr)
library(dplyr)
library(nestcolor)

# original ARM value = dose value
arm_mapping <- list(
  "A: Drug X" = "150mg QD", "B: Placebo" = "Placebo", "C: Combination" = "Combination"
)
color_manual <- c("150mg QD" = "thistle", "Placebo" = "orange", "Combination" = "steelblue")
type_manual <- c("150mg QD" = "solid", "Placebo" = "dashed", "Combination" = "dotted")

ADSL <- rADSL %>% filter(!(ARM == "B: Placebo" & AGE < 40))
ADLB <- rADLB
ADLB <- right_join(ADLB, ADSL[, c("STUDYID", "USUBJID")])
var_labels <- lapply(ADLB, function(x) attributes(x)$label)

ADLB <- ADLB %>%
  mutate(AVISITCD = case_when(
    AVISIT == "SCREENING" ~ "SCR",
    AVISIT == "BASELINE" ~ "BL",
    grepl("WEEK", AVISIT) ~
      paste(
        "W",
        trimws(
          substr(
            AVISIT,
            start = 6,
            stop = str_locate(AVISIT, "DAY") - 1
          )
        )
      ),
    TRUE ~ NA_character_
  )) %>%
  mutate(AVISITCDN = case_when(
    AVISITCD == "SCR" ~ -2,
    AVISITCD == "BL" ~ 0,
    grepl("W", AVISITCD) ~ as.numeric(gsub("\\D+", "", AVISITCD)),
    TRUE ~ NA_real_
  )) %>%
  # use ARMCD values to order treatment in visualization legend
  mutate(TRTORD = ifelse(grepl("C", ARMCD), 1,
                         ifelse(grepl("B", ARMCD), 2,
                                ifelse(grepl("A", ARMCD), 3, NA)
                         )
  )) %>%
  mutate(ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))])) %>%
  mutate(ARM = factor(ARM) %>%
           reorder(TRTORD))
attr(ADLB[["ARM"]], "label") <- var_labels[["ARM"]]

attr(ADLB[["AVISITCDN"]], "label") <- "CUSTOM LABEL FOR THE AXIS LABEL"
g_lineplot(
  label = "Line Plot",
  data = ADLB,
  biomarker_var = "PARAMCD",
  biomarker = "CRP",
  value_var = "AVAL",
  trt_group = "ARM",
  shape = NULL,
  time = "AVISITCDN",
  color_manual = color_manual,
  line_type = type_manual,
  median = FALSE,
  hline_arb = c(.9, 1.1, 1.2, 1.5),
  hline_arb_color = c("green", "red", "blue", "pink"),
  hline_arb_label = c("A", "B", "C", "D"),
  xtick = c(0, 1, 5),
  xlabel = c("Baseline", "Week 1", "Week 5"),
  rotate_xlab = FALSE,
  plot_height = 600
)

attr(ADLB[["AVISITCDN"]], "label") <- NULL
g_lineplot(
  label = "Line Plot",
  data = ADLB,
  biomarker_var = "PARAMCD",
  biomarker = "CRP",
  value_var = "AVAL",
  trt_group = "ARM",
  shape = NULL,
  time = "AVISITCDN",
  color_manual = color_manual,
  line_type = type_manual,
  median = FALSE,
  hline_arb = c(.9, 1.1, 1.2, 1.5),
  hline_arb_color = c("green", "red", "blue", "pink"),
  hline_arb_label = c("A", "B", "C", "D"),
  xtick = c(0, 1, 5),
  xlabel = c("Baseline", "Week 1", "Week 5"),
  rotate_xlab = FALSE,
  plot_height = 600
)

```

# Custom label from attribute

<img width="460" alt="image" src="https://github.com/user-attachments/assets/bd1e12ed-1b57-4ebf-bd0f-813e90d59fd1">

# No attribute, so take column name

<img width="455" alt="image" src="https://github.com/user-attachments/assets/11ee8d32-2def-4063-9b37-41b6d1299c16">

2024-10-15 04:03 UTC, donyunardi requested changes
Thanks for this alternative @m7pr. 

This approach will help us stay consistent with spaghettiplot.

However, I'm not seeing the same result you're getting with spaghettiplot using your example code. For me, it always shows only "AVISITCD."

This seems to happen because this line removes the label attribute:
https://github.com/insightsengineering/goshawk/blob/d8439aabbf609eea709b55ffa2eab61790d1770e/R/g_spaghettiplot.R#L262-L268

Could you please double check?

2024-10-15 07:10 UTC, m7pr commented
Ah sorry @donyunardi - I made a commit locally, but didn't push it.. Pushing it now

2024-10-15 07:11 UTC, m7pr commented on R/g_spaghettiplot.R
> +  gxlab <- if (is.null(attr(data[[time]], "label"))) time else attr(data[[time]], "label")
This is moved before `data[[time]]` gets overwritten : )

2024-10-16 06:39 UTC, donyunardi approved these changes

2024-10-16 07:11 UTC, merged